-- CreateTable
CREATE TABLE "User" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "firstName" STRING NOT NULL,
    "lastName" STRING NOT NULL,
    "hashedPassword" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "crdb_region" "crdb_internal_region",

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Movement" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "authorId" INT8 NOT NULL,
    "name" STRING NOT NULL,
    "split" STRING,
    "description" STRING,
    "warmupSets" STRING,
    "workingSets" STRING,
    "rpe" STRING,
    "restTime" INT4,
    "crdb_region" "crdb_internal_region",

    CONSTRAINT "Movement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MovementLog" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "movementId" INT8 NOT NULL,
    "sets" INT4 NOT NULL,
    "reps" INT4 NOT NULL,
    "load" DECIMAL(65,30) NOT NULL,
    "crdb_region" "crdb_internal_region",

    CONSTRAINT "MovementLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "Movement" ADD CONSTRAINT "Movement_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MovementLog" ADD CONSTRAINT "MovementLog_movementId_fkey" FOREIGN KEY ("movementId") REFERENCES "Movement"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
